# Generated by Django 6.1.1 on 2026-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attendance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
