# Generated by Django 6.1.1 on 2026-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
